name: Docker Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login   
      run: docker login -u ${{secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_PASSWORD}}
        
    - name: Build Docker image
      run: docker build -t match_maven .
      
    - name: Docker Push 
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/match_maven:latest
